version: '3.8'

services:
  db:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: xyz-bank
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: false
      MYSQL_ROOT_HOST: "%"